/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows.$workflowId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ObjectsObjectIdRouteImport } from './routes/objects.$objectId'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsObjectIdRoute = ObjectsObjectIdRouteImport.update({
  id: '/objects/$objectId',
  path: '/objects/$objectId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents': typeof AgentsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/objects': typeof ObjectsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$agentId'
    | '/campaigns/$campaignId'
    | '/objects/$objectId'
    | '/tasks/$taskId'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/campaigns/'
    | '/dashboards/'
    | '/objects/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/campaigns/$campaignId'
    | '/objects/$objectId'
    | '/tasks/$taskId'
    | '/workflows/$workflowId'
    | '/agents'
    | '/campaigns'
    | '/dashboards'
    | '/objects'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/agents/$agentId'
    | '/campaigns/$campaignId'
    | '/objects/$objectId'
    | '/tasks/$taskId'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/campaigns/'
    | '/dashboards/'
    | '/objects/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  ObjectsObjectIdRoute: typeof ObjectsObjectIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$objectId': {
      id: '/objects/$objectId'
      path: '/objects/$objectId'
      fullPath: '/objects/$objectId'
      preLoaderRoute: typeof ObjectsObjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  ObjectsObjectIdRoute: ObjectsObjectIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
