/** App shell: 3-panel resizable layout (sidebar | main+chat | agent). */

import { lazy, Suspense, useEffect } from "react";
import { Outlet, createRootRoute, Link } from "@tanstack/react-router";
import {
  Group,
  Panel,
  Separator,
  useDefaultLayout,
  usePanelCallbackRef,
  type PanelImperativeHandle,
} from "react-resizable-panels";
import { Activity, Bot, Boxes, ChevronsLeft, ChevronsRight, FolderKanban, Github, LayoutDashboard, MousePointerClick, Workflow } from "lucide-react";
import { useInfo } from "../api/queries";
import { fmtDuration, toEpochSec } from "../lib/format";
import { useInspectorStore, type GraphInspectorDoc } from "../stores/inspectorStore";

const ChatPanel = lazy(() =>
  import("../components/chat/ChatPanel").then((m) => ({ default: m.ChatPanel })),
);

export const Route = createRootRoute({ component: AppShell });

const NAV = [
  { to: "/", label: "Overview", icon: Activity },
  { to: "/campaigns", label: "Campaigns", icon: FolderKanban },
  { to: "/workflows", label: "Workflows", icon: Workflow },
  { to: "/objects", label: "Artifacts", icon: Boxes },
  { to: "/agents", label: "Agents", icon: Bot },
  { to: "/dashboards", label: "Dashboard configs", icon: LayoutDashboard },
] as const;

function JsonSyntax({ value, depth = 0 }: { value: unknown; depth?: number }) {
  const pad = "  ".repeat(depth);
  const nextPad = "  ".repeat(depth + 1);
  if (value === null) return <span className="text-fg-muted">null</span>;
  if (typeof value === "string") return <span className="text-ok">"{value}"</span>;
  if (typeof value === "number") return <span className="text-warn">{value}</span>;
  if (typeof value === "boolean") return <span className="text-accent">{String(value)}</span>;
  if (Array.isArray(value)) {
    if (value.length === 0) return <span>[]</span>;
    return (
      <>
        [
        {value.map((item, idx) => (
          <span key={idx}>
            {"\n"}
            {nextPad}
            <JsonSyntax value={item} depth={depth + 1} />
            {idx < value.length - 1 ? "," : ""}
          </span>
        ))}
        {"\n"}
        {pad}]
      </>
    );
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return <span>{"{}"}</span>;
    return (
      <>
        {"{"}
        {entries.map(([key, item], idx) => (
          <span key={key}>
            {"\n"}
            {nextPad}
            <span className="text-running">"{key}"</span>: <JsonSyntax value={item} depth={depth + 1} />
            {idx < entries.length - 1 ? "," : ""}
          </span>
        ))}
        {"\n"}
        {pad}
        {"}"}
      </>
    );
  }
  return <span>{String(value)}</span>;
}

function PrettyValue({ value }: { value: unknown }) {
  if (typeof value !== "object" || value === null) {
    return <span className="font-mono text-[11px] break-all">{String(value)}</span>;
  }
  return (
    <pre className="max-h-56 overflow-auto whitespace-pre-wrap rounded bg-surface-2 p-2 font-mono text-[11px]">
      <JsonSyntax value={value} />
    </pre>
  );
}

function Field({ label, value }: { label: string; value: unknown }) {
  if (value === null || value === undefined || value === "") return null;
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-fg-muted text-[10px]">{label}</span>
      <PrettyValue value={value} />
    </div>
  );
}

function GeneratedBy({ value }: { value: unknown }) {
  const entries = Array.isArray(value) ? value : [];
  if (entries.length === 0) return null;
  return (
    <div className="space-y-1">
      <span className="text-fg-muted text-[10px]">Generated by</span>
      {entries.map((entry, idx) => {
        const item = entry as Record<string, unknown>;
        return (
          <div key={idx} className="rounded bg-surface-2 p-2">
            <Field label="Activity" value={item["activity"]} />
            <Field label="task_id" value={item["task_id"]} />
          </div>
        );
      })}
    </div>
  );
}

/** Compact duration-stats table used in the aggregated-activity inspector. */
function DurationStats({ ds }: { ds: Record<string, unknown> }) {
  const fmt = (v: unknown) => (typeof v === "number" ? fmtDuration(v) : "—");
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-fg-muted text-[10px]">duration ({String(ds["count"])} tasks)</span>
      <div className="rounded bg-surface-2 px-2 py-1.5 font-mono text-[11px] space-y-0.5">
        {(["mean", "min", "p25", "p50", "p75", "max"] as const).map((k) => (
          <div key={k} className="flex justify-between gap-4">
            <span className="text-fg-muted">{k}</span>
            <span>{fmt(ds[k])}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function GraphInspector({ kind, data }: { kind: "task" | "activity" | "dataflow"; data: GraphInspectorDoc }) {
  const stats = data.stats;
  if (kind === "task") {
    const start = toEpochSec(stats["started_at"] as Parameters<typeof toEpochSec>[0]);
    const end = toEpochSec(stats["ended_at"] as Parameters<typeof toEpochSec>[0]);
    const duration = start !== null && end !== null ? end - start : null;
    return (
      <div className="space-y-1.5">
        <Field label="Activity" value={data.label} />
        <Field label="task_id" value={stats["task_id"]} />
        <Field label="status" value={stats["status"]} />
        <Field label="duration" value={fmtDuration(duration)} />
        <Field label="agent_id" value={stats["agent_id"]} />
        <Field label="source_agent_id" value={stats["source_agent_id"]} />
        <Field label="subtype" value={stats["subtype"]} />
        <Field label="Used" value={stats["used"]} />
        <Field label="Generated" value={stats["generated"]} />
      </div>
    );
  }

  if (kind === "activity") {
    const ds = stats["duration_stats"] as Record<string, unknown> | null | undefined;
    if (ds) {
      // Aggregated coarse-graph activity — show duration stats summary.
      return (
        <div className="space-y-1.5">
          <Field label="Activity" value={data.label} />
          <Field label="tasks" value={stats["task_count"]} />
          <DurationStats ds={ds} />
          <Field label="task_ids" value={stats["task_ids"]} />
        </div>
      );
    }
    return (
      <div className="space-y-1.5">
        <Field label="Activity" value={data.label} />
        <Field label="task_count" value={stats["task_count"]} />
        <Field label="started_at" value={stats["started_at"]} />
        <Field label="ended_at" value={stats["ended_at"]} />
        <Field label="duration" value={stats["duration"]} />
        <Field label="status_counts" value={stats["status_counts"]} />
        <Field label="agent_id" value={stats["agent_id"]} />
        <Field label="source_agent_id" value={stats["source_agent_id"]} />
        <Field label="task_ids" value={stats["task_ids"]} />
      </div>
    );
  }

  // dataflow (chunk node)
  if (stats["chunk_count"] != null) {
    const itemStats = stats["item_stats"] as Record<string, Record<string, unknown>> | null | undefined;
    return (
      <div className="space-y-1.5">
        <Field label="label" value={data.label} />
        <Field label="chunks" value={stats["chunk_count"]} />
        <Field label="activities" value={stats["activities"]} />
        {itemStats && Object.keys(itemStats).length > 0
          ? Object.entries(itemStats).map(([key, ds]) => (
              <div key={key} className="flex flex-col gap-0.5">
                <span className="text-fg-muted text-[10px]">{key}</span>
                <div className="rounded bg-surface-2 px-2 py-1.5 font-mono text-[11px] space-y-0.5">
                  {(["mean", "min", "p25", "p50", "p75", "max"] as const).map((k) => (
                    <div key={k} className="flex justify-between gap-4">
                      <span className="text-fg-muted">{k}</span>
                      <span>{typeof ds[k] === "number" ? (ds[k] as number).toFixed(4) : "—"}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))
          : <Field label="chunk_ids" value={stats["original_ids"]} />}
      </div>
    );
  }

  return (
    <div className="space-y-1.5">
      <Field label="kind" value={stats["kind"]} />
      <Field label="items" value={stats["items"]} />
      <GeneratedBy value={stats["generated_by"]} />
    </div>
  );
}

function AppShell() {
  const { data: info } = useInfo();
  const [leftHandle, leftRef] = usePanelCallbackRef();
  const [rightHandle, rightRef] = usePanelCallbackRef();
  const [chatHandle, chatRef] = usePanelCallbackRef();
  const hLayout = useDefaultLayout({ id: "flowcept-shell-h" });
  const vLayout = useDefaultLayout({ id: "flowcept-shell-v" });
  const inspectorEntity = useInspectorStore((s) => s.entity);

  useEffect(() => {
    if (rightHandle && hLayout.defaultLayout === undefined) {
      rightHandle.collapse();
    }
  }, [rightHandle, hLayout.defaultLayout]);

  useEffect(() => {
    if (inspectorEntity && rightHandle?.isCollapsed()) {
      rightHandle.expand();
    }
  }, [inspectorEntity, rightHandle]);

  return (
    <Group
      orientation="horizontal"
      className="h-full"
      defaultLayout={hLayout.defaultLayout}
      onLayoutChanged={hLayout.onLayoutChanged}
    >
      {/* Left: nav sidebar */}
      <Panel
        panelRef={leftRef}
        defaultSize={15}
        minSize={12}
        collapsible
        collapsedSize={0}
        className="flex flex-col border-r border-border bg-surface"
      >
        <div className="flex justify-center px-4 py-5">
          <a href="https://flowcept.org/" target="_blank" rel="noreferrer" title="flowcept.org">
            <img src="/flowcept-logo.png" alt="Flowcept" className="h-14 w-auto" />
          </a>
        </div>
        <nav className="flex-1 space-y-0.5 px-2">
          {NAV.map(({ to, label, icon: Icon }) => (
            <Link
              key={to}
              to={to}
              activeOptions={{ exact: to === "/" }}
              className="text-fg-muted flex items-center gap-2.5 rounded-md px-2.5 py-2 text-[13px] hover:bg-surface-2 hover:text-fg"
              activeProps={{ className: "bg-accent-soft !text-fg" }}
            >
              <Icon size={15} />
              {label}
            </Link>
          ))}
        </nav>
        <div className="space-y-2 border-t border-border px-2 py-3">
          <a href="/docs" target="_blank" rel="noreferrer" className="text-fg-muted hover:text-fg block px-2.5 text-[11px]">
            API docs ↗
          </a>
          <div className="flex items-center gap-3 px-2.5 pt-1">
            <a href="https://github.com/ORNL/flowcept" target="_blank" rel="noreferrer" title="GitHub"
               className="text-fg-muted hover:text-fg flex items-center gap-1">
              <Github size={13} />
              <span className="text-[11px]">GitHub</span>
            </a>
            <a
              href="https://flowcept.readthedocs.io/en/latest"
              target="_blank"
              rel="noreferrer"
              className="text-fg-muted hover:text-fg text-[11px]"
            >
              Docs ↗
            </a>
            {info?.version && (
              <span className="text-fg-muted ml-auto text-[10px]">v{info.version}</span>
            )}
          </div>
          <button
            onClick={() => leftHandle?.collapse()}
            className="text-fg-muted hover:text-fg flex w-full items-center gap-1.5 px-2.5 py-1 text-[11px]"
            title="Collapse sidebar"
          >
            <ChevronsLeft size={13} /> Collapse
          </button>
        </div>
      </Panel>

      {/* Vertical resize handle between left and center, with right-panel toggle */}
      <Separator className="bg-border hover:bg-accent/60 transition-colors w-px relative flex items-center justify-center">
        <button
          onClick={() => {
            if (rightHandle?.isCollapsed()) {
              rightHandle.expand();
            } else {
              rightHandle?.collapse();
            }
          }}
          className="absolute right-[-10px] top-1/2 -translate-y-1/2 z-10 flex h-6 w-5 items-center justify-center rounded-r border border-border bg-surface text-fg-muted hover:text-fg text-[10px]"
          title="Toggle inspector panel"
        >
          <ChevronsRight size={11} />
        </button>
      </Separator>

      {/* Center: main content + chat */}
      <Panel minSize={30} className="flex flex-col min-w-0">
        <Group
          orientation="vertical"
          className="flex-1 h-full"
          defaultLayout={vLayout.defaultLayout}
          onLayoutChanged={vLayout.onLayoutChanged}
        >
          <Panel minSize={30} className="min-h-0 overflow-y-auto">
            <Outlet />
          </Panel>
          <Separator className="bg-border hover:bg-accent/60 transition-colors h-px" />
          <Panel
            panelRef={chatRef}
            defaultSize={20}
            minSize={6}
            collapsible
            collapsedSize={5}
          >
            <Suspense fallback={null}>
              <ChatPanel panelHandle={chatHandle} />
            </Suspense>
          </Panel>
        </Group>
      </Panel>

      {/* Vertical resize handle between center and right */}
      <Separator className="bg-border hover:bg-accent/60 transition-colors w-px" />

      {/* Right: inspector panel */}
      <Panel
        panelRef={rightRef}
        defaultSize={20}
        minSize={15}
        collapsible
        collapsedSize={0}
        className="flex flex-col border-l border-border bg-surface"
      >
        <div className="border-b border-border px-4 py-2 flex items-center justify-between">
          <span className="text-sm font-medium">Inspector</span>
          {inspectorEntity && (
            <button onClick={() => useInspectorStore.getState().clear()} className="text-fg-muted hover:text-fg text-xs">✕</button>
          )}
        </div>
        {inspectorEntity ? (
          <div className="flex-1 overflow-y-auto p-3 space-y-2 text-xs">
            <div className="text-fg-muted font-medium uppercase tracking-wide text-[10px]">
              {inspectorEntity.kind === "object"
                ? "Artifact"
                : inspectorEntity.kind === "task"
                ? "Task"
                : inspectorEntity.kind === "activity"
                ? "Activity"
                : inspectorEntity.kind === "chart"
                ? inspectorEntity.title
                : "Provenance"}
            </div>
            {inspectorEntity.kind === "object" && (
              <div className="space-y-1.5">
                {Object.entries(inspectorEntity.data)
                  .filter(([, v]) => v !== null && v !== undefined && v !== "")
                  .map(([k, v]) => (
                    <Field key={k} label={k} value={v} />
                  ))}
              </div>
            )}
            {inspectorEntity.kind === "chart" && (() => {
              const cols = inspectorEntity.rows.length ? Object.keys(inspectorEntity.rows[0]) : [];
              return (
                <div className="overflow-x-auto">
                  <table className="w-full text-[11px]">
                    <thead>
                      <tr className="text-fg-muted text-left">
                        {cols.map((c) => (
                          <th key={c} className="border-b border-border px-2 py-1.5 font-medium whitespace-nowrap">{c}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {inspectorEntity.rows.map((r, i) => (
                        <tr key={i} className="border-b border-border/40">
                          {cols.map((c) => {
                            const v = r[c];
                            const display = v === null || v === undefined ? "—"
                              : typeof v === "number" ? (Number.isInteger(v) ? String(v) : v.toFixed(4))
                              : String(v);
                            return <td key={c} className="px-2 py-1 whitespace-nowrap">{display}</td>;
                          })}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              );
            })()}
            {inspectorEntity.kind !== "object" && inspectorEntity.kind !== "chart" && (
              <GraphInspector kind={inspectorEntity.kind} data={inspectorEntity.data} />
            )}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center flex-1 text-fg-muted text-xs gap-2 p-4 text-center">
            <MousePointerClick size={22} className="text-accent/60" />
            <span>Click on an entity (workflow, campaign, or activity) to inspect it here.</span>
          </div>
        )}
      </Panel>
    </Group>
  );
}

export type { PanelImperativeHandle };
