/**
 * Collapses a fine-grained PROV dataflow graph into an activity-level
 * "coarse" graph.
 *
 * - All task nodes sharing the same activity_id are merged into one super-node.
 * - All chunk nodes generated by the same set of activities are merged into
 *   one super-node.
 * - Parallel edges between the same super-node pair are de-duplicated and
 *   counted so the renderer can draw them as double/thick lines.
 * - Duration statistics (min/max/mean/quartiles) are computed for task
 *   super-nodes from started_at / ended_at fields.
 */

import type { DataflowGraph } from "../api/queries";
import { toEpochSec } from "./format";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface QuantileStats {
  count: number;
  min: number;
  max: number;
  mean: number;
  p25: number;
  p50: number;
  p75: number;
}

export interface CoarseNode {
  id: string;
  kind: "task" | "chunk";
  label: string;
  count: number;
  originalIds: string[];
  durationStats?: QuantileStats;
  activities: string[];
  itemStats?: Record<string, QuantileStats>;
}

export interface CoarseEdge {
  source: string;
  target: string;
  relation: string;
  count: number;
}

export interface CoarseGraph {
  nodes: CoarseNode[];
  edges: CoarseEdge[];
  truncated: boolean;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function quantiles(values: number[]): QuantileStats {
  const sorted = [...values].sort((a, b) => a - b);
  const n = sorted.length;
  const pct = (p: number) => sorted[Math.min(Math.floor(p * n), n - 1)];
  const sum = sorted.reduce((a, b) => a + b, 0);
  return {
    count: n,
    min: sorted[0],
    max: sorted[n - 1],
    mean: sum / n,
    p25: pct(0.25),
    p50: pct(0.5),
    p75: pct(0.75),
  };
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/** Reduces a fine-grained DataflowGraph to an activity-level CoarseGraph. */
export function coarsenGraph(graph: DataflowGraph): CoarseGraph {
  type OriginalNode = DataflowGraph["nodes"][number];

  // ── 1. Map task nodes → activity id ──────────────────────────────────────
  const taskActivity = new Map<string, string>(); // nodeId → activityId
  for (const n of graph.nodes) {
    if (n.kind === "task") {
      const activity = (n.stats?.activity_id as string | undefined) || n.label || n.id;
      taskActivity.set(n.id, activity);
    }
  }

  // ── 2. Build adjacency for chunk generation and consumption ──────────────
  const chunkGenerators = new Map<string, string[]>(); // chunkId → [taskId]
  const chunkConsumers = new Map<string, string[]>(); // chunkId → [taskId]
  for (const e of graph.edges) {
    if (e.relation === "generated") {
      if (!chunkGenerators.has(e.target)) chunkGenerators.set(e.target, []);
      chunkGenerators.get(e.target)!.push(e.source);
    } else if (e.relation === "used") {
      if (!chunkConsumers.has(e.source)) chunkConsumers.set(e.source, []);
      chunkConsumers.get(e.source)!.push(e.target);
    }
  }

  // ── 3. Assign each original node to a coarse super-node id ───────────────
  const nodeToSuper = new Map<string, string>(); // originalId → superNodeId

  const taskGroups = new Map<string, OriginalNode[]>();
  for (const n of graph.nodes) {
    if (n.kind !== "task") continue;
    const activity = taskActivity.get(n.id)!;
    const sid = `activity:${activity}`;
    nodeToSuper.set(n.id, sid);
    if (!taskGroups.has(sid)) taskGroups.set(sid, []);
    taskGroups.get(sid)!.push(n);
  }

  const chunkGroups = new Map<string, OriginalNode[]>();
  for (const n of graph.nodes) {
    if (n.kind === "task") continue;

    const genActivities = (chunkGenerators.get(n.id) ?? [])
      .map((tid) => taskActivity.get(tid))
      .filter((a): a is string => a !== undefined)
      .sort();

    let sid: string;
    if (genActivities.length > 0) {
      sid = `chunks_from:${genActivities.join("+")}`;
    } else {
      const conActivities = (chunkConsumers.get(n.id) ?? [])
        .map((tid) => taskActivity.get(tid))
        .filter((a): a is string => a !== undefined)
        .sort();
      sid = conActivities.length > 0 ? `chunks_to:${conActivities.join("+")}` : `chunk:${n.id}`;
    }

    nodeToSuper.set(n.id, sid);
    if (!chunkGroups.has(sid)) chunkGroups.set(sid, []);
    chunkGroups.get(sid)!.push(n);
  }

  // ── 4. Build CoarseNodes ─────────────────────────────────────────────────
  const coarseNodes: CoarseNode[] = [];

  for (const [sid, nodes] of taskGroups) {
    const activity = sid.slice("activity:".length);
    const durations: number[] = [];
    for (const n of nodes) {
      const s = toEpochSec(n.stats?.started_at as Parameters<typeof toEpochSec>[0]);
      const e = toEpochSec(n.stats?.ended_at as Parameters<typeof toEpochSec>[0]);
      if (s !== null && e !== null && e > s) durations.push(e - s);
    }
    coarseNodes.push({
      id: sid,
      kind: "task",
      label: activity,
      count: nodes.length,
      originalIds: nodes.map((n) => n.id),
      durationStats: durations.length > 0 ? quantiles(durations) : undefined,
      activities: [activity],
    });
  }

  for (const [sid, nodes] of chunkGroups) {
    const activities = sid.startsWith("chunks_from:")
      ? sid.slice("chunks_from:".length).split("+")
      : sid.startsWith("chunks_to:")
        ? sid.slice("chunks_to:".length).split("+")
        : [];
    const label =
      nodes.length === 1
        ? nodes[0].label || "data"
        : activities.length > 0
          ? `data (${activities.join(" + ")})`
          : "data";

    // Collect numeric values per item key across all chunks in the group.
    const keyValues = new Map<string, number[]>();
    for (const n of nodes) {
      const items = n.stats?.items as Record<string, unknown> | undefined;
      if (!items) continue;
      for (const [k, v] of Object.entries(items)) {
        if (typeof v !== "number") continue;
        if (!keyValues.has(k)) keyValues.set(k, []);
        keyValues.get(k)!.push(v);
      }
    }
    const itemStats: Record<string, QuantileStats> = {};
    for (const [k, vals] of keyValues) itemStats[k] = quantiles(vals);

    coarseNodes.push({
      id: sid,
      kind: "chunk",
      label,
      count: nodes.length,
      originalIds: nodes.map((n) => n.id),
      activities,
      itemStats: keyValues.size > 0 ? itemStats : undefined,
    });
  }

  // ── 5. Remap and de-duplicate edges ──────────────────────────────────────
  const edgeMap = new Map<string, CoarseEdge>();
  for (const e of graph.edges) {
    const src = nodeToSuper.get(e.source);
    const tgt = nodeToSuper.get(e.target);
    if (!src || !tgt || src === tgt) continue;
    const key = `${src}|${tgt}|${e.relation}`;
    if (edgeMap.has(key)) {
      edgeMap.get(key)!.count++;
    } else {
      edgeMap.set(key, { source: src, target: tgt, relation: e.relation, count: 1 });
    }
  }

  return { nodes: coarseNodes, edges: [...edgeMap.values()], truncated: graph.truncated };
}
