/**
 * TDD tests for coarsenGraph — activity-level aggregation of the fine-grained
 * PROV dataflow graph.
 *
 * All tests use plain graph data (no React, no DOM).
 */

import { describe, it, expect } from "vitest";
import { coarsenGraph } from "../src/lib/coarsenGraph";
import type { DataflowGraph } from "../src/api/queries";

// ---------------------------------------------------------------------------
// Graph fixtures
// ---------------------------------------------------------------------------

/** Two "train" task nodes + one "eval" task node, each generating a chunk. */
const TWO_TRAIN_ONE_EVAL: DataflowGraph = {
  level: "coarse",
  truncated: false,
  nodes: [
    { id: "task:t1", kind: "task", label: "train", stats: { activity_id: "train", started_at: 0, ended_at: 5 } },
    { id: "task:t2", kind: "task", label: "train", stats: { activity_id: "train", started_at: 10, ended_at: 20 } },
    { id: "task:t3", kind: "task", label: "eval",  stats: { activity_id: "eval",  started_at: 25, ended_at: 28 } },
    { id: "chunk:c1", kind: "chunk", label: "loss", stats: {} },
    { id: "chunk:c2", kind: "chunk", label: "loss", stats: {} },
  ],
  edges: [
    { source: "task:t1", target: "chunk:c1", relation: "generated" },
    { source: "task:t2", target: "chunk:c2", relation: "generated" },
    { source: "chunk:c1", target: "task:t3", relation: "used" },
    { source: "chunk:c2", target: "task:t3", relation: "used" },
  ],
};

// ---------------------------------------------------------------------------
// Tests: node coarsening
// ---------------------------------------------------------------------------

describe("coarsenGraph — node aggregation", () => {
  it("collapses task nodes with the same activity_id into one super-node", () => {
    const { nodes } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    const taskNodes = nodes.filter((n) => n.kind === "task");
    expect(taskNodes).toHaveLength(2);
    expect(taskNodes.find((n) => n.label === "train")?.count).toBe(2);
    expect(taskNodes.find((n) => n.label === "eval")?.count).toBe(1);
  });

  it("collapses chunk nodes generated by the same activity into one super-node", () => {
    const { nodes } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    const chunkNodes = nodes.filter((n) => n.kind !== "task");
    expect(chunkNodes).toHaveLength(1);
    expect(chunkNodes[0].count).toBe(2);
  });

  it("preserves the original node ids in originalIds", () => {
    const { nodes } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    const trainNode = nodes.find((n) => n.label === "train");
    expect(trainNode?.originalIds).toHaveLength(2);
    expect(trainNode?.originalIds).toContain("task:t1");
    expect(trainNode?.originalIds).toContain("task:t2");
  });
});

// ---------------------------------------------------------------------------
// Tests: edge coarsening
// ---------------------------------------------------------------------------

describe("coarsenGraph — edge aggregation", () => {
  it("counts parallel used-edges between the same super-node pair", () => {
    const { edges } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    const usedEdges = edges.filter((e) => e.relation === "used");
    expect(usedEdges).toHaveLength(1);
    expect(usedEdges[0].count).toBe(2);
  });

  it("counts parallel generated-edges between the same super-node pair", () => {
    const { edges } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    const genEdges = edges.filter((e) => e.relation === "generated");
    expect(genEdges).toHaveLength(1);
    expect(genEdges[0].count).toBe(2);
  });

  it("does not emit self-loop edges", () => {
    const { edges } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    expect(edges.every((e) => e.source !== e.target)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Tests: duration stats
// ---------------------------------------------------------------------------

describe("coarsenGraph — duration stats", () => {
  it("computes min, max, mean for task super-nodes with duration data", () => {
    const { nodes } = coarsenGraph(TWO_TRAIN_ONE_EVAL);
    const train = nodes.find((n) => n.label === "train");
    // durations: 5 (0→5) and 10 (10→20)
    expect(train?.durationStats?.count).toBe(2);
    expect(train?.durationStats?.min).toBe(5);
    expect(train?.durationStats?.max).toBe(10);
    expect(train?.durationStats?.mean).toBe(7.5);
  });

  it("returns undefined durationStats when no timing data is available", () => {
    const noTiming: DataflowGraph = {
      level: "coarse",
      truncated: false,
      nodes: [
        { id: "task:x", kind: "task", label: "step", stats: { activity_id: "step" } },
      ],
      edges: [],
    };
    const { nodes } = coarsenGraph(noTiming);
    expect(nodes[0].durationStats).toBeUndefined();
  });

  it("computes p25, p50, p75 quartiles", () => {
    const fourTasks: DataflowGraph = {
      level: "coarse",
      truncated: false,
      nodes: [
        { id: "task:a", kind: "task", label: "step", stats: { activity_id: "step", started_at: 0, ended_at: 2 } },
        { id: "task:b", kind: "task", label: "step", stats: { activity_id: "step", started_at: 0, ended_at: 4 } },
        { id: "task:c", kind: "task", label: "step", stats: { activity_id: "step", started_at: 0, ended_at: 6 } },
        { id: "task:d", kind: "task", label: "step", stats: { activity_id: "step", started_at: 0, ended_at: 8 } },
      ],
      edges: [],
    };
    const { nodes } = coarsenGraph(fourTasks);
    const stats = nodes[0].durationStats!;
    expect(stats.count).toBe(4);
    expect(stats.min).toBe(2);
    expect(stats.max).toBe(8);
    // sorted: [2,4,6,8]; p25=index 1=4, p50=index 2=6, p75=index 3=8 (floor-based percentile)
    expect(stats.p25).toBe(4);
    expect(stats.p50).toBe(6);
    expect(stats.p75).toBe(8);
  });
});

// ---------------------------------------------------------------------------
// Tests: ISO string timestamps
// ---------------------------------------------------------------------------

describe("coarsenGraph — ISO string timestamps", () => {
  it("parses ISO string started_at / ended_at into duration stats", () => {
    const isoTasks: DataflowGraph = {
      level: "fine",
      truncated: false,
      nodes: [
        {
          id: "task:i1", kind: "task", label: "train",
          stats: { activity_id: "train", started_at: "2024-01-01T00:00:00Z", ended_at: "2024-01-01T00:00:05Z" },
        },
        {
          id: "task:i2", kind: "task", label: "train",
          stats: { activity_id: "train", started_at: "2024-01-01T00:00:10Z", ended_at: "2024-01-01T00:00:20Z" },
        },
      ],
      edges: [],
    };
    const { nodes } = coarsenGraph(isoTasks);
    const train = nodes.find((n) => n.label === "train");
    // durations: 5s and 10s
    expect(train?.durationStats?.count).toBe(2);
    expect(train?.durationStats?.min).toBeCloseTo(5, 0);
    expect(train?.durationStats?.max).toBeCloseTo(10, 0);
    expect(train?.durationStats?.mean).toBeCloseTo(7.5, 0);
  });

  it("handles mixed numeric epoch and ISO string timestamps in the same group", () => {
    const mixed: DataflowGraph = {
      level: "fine",
      truncated: false,
      nodes: [
        {
          id: "task:m1", kind: "task", label: "step",
          stats: { activity_id: "step", started_at: 0, ended_at: 3 },
        },
        {
          id: "task:m2", kind: "task", label: "step",
          stats: { activity_id: "step", started_at: "2024-01-01T00:00:07Z", ended_at: "2024-01-01T00:00:10Z" },
        },
      ],
      edges: [],
    };
    const { nodes } = coarsenGraph(mixed);
    const step = nodes.find((n) => n.label === "step");
    // durations: 3s and 3s
    expect(step?.durationStats?.count).toBe(2);
    expect(step?.durationStats?.min).toBeCloseTo(3, 0);
    expect(step?.durationStats?.max).toBeCloseTo(3, 0);
  });
});

// ---------------------------------------------------------------------------
// Tests: chunk item statistics
// ---------------------------------------------------------------------------

describe("coarsenGraph — chunk item stats", () => {
  it("computes per-key numeric stats across all chunks in a group", () => {
    const withItems: DataflowGraph = {
      level: "fine",
      truncated: false,
      nodes: [
        { id: "task:t1", kind: "task", label: "train", stats: { activity_id: "train" } },
        { id: "task:t2", kind: "task", label: "train", stats: { activity_id: "train" } },
        {
          id: "chunk:c1", kind: "chunk", label: "metrics",
          stats: { items: { val_loss: 0.8, val_accuracy: 0.6 } },
        },
        {
          id: "chunk:c2", kind: "chunk", label: "metrics",
          stats: { items: { val_loss: 0.4, val_accuracy: 0.9 } },
        },
      ],
      edges: [
        { source: "task:t1", target: "chunk:c1", relation: "generated" },
        { source: "task:t2", target: "chunk:c2", relation: "generated" },
      ],
    };
    const { nodes } = coarsenGraph(withItems);
    const chunkNode = nodes.find((n) => n.kind === "chunk");
    expect(chunkNode).toBeDefined();
    const itemStats = chunkNode?.itemStats;
    expect(itemStats).toBeDefined();

    // val_loss: [0.8, 0.4] → min=0.4, max=0.8
    expect(itemStats?.["val_loss"]?.min).toBeCloseTo(0.4, 5);
    expect(itemStats?.["val_loss"]?.max).toBeCloseTo(0.8, 5);
    expect(itemStats?.["val_loss"]?.count).toBe(2);

    // val_accuracy: [0.6, 0.9] → min=0.6, max=0.9
    expect(itemStats?.["val_accuracy"]?.min).toBeCloseTo(0.6, 5);
    expect(itemStats?.["val_accuracy"]?.max).toBeCloseTo(0.9, 5);
  });

  it("skips non-numeric item values", () => {
    const withMixed: DataflowGraph = {
      level: "fine",
      truncated: false,
      nodes: [
        { id: "task:t1", kind: "task", label: "train", stats: { activity_id: "train" } },
        {
          id: "chunk:c1", kind: "chunk", label: "metrics",
          stats: { items: { val_loss: 0.5, model_id: "abc123" } },
        },
      ],
      edges: [
        { source: "task:t1", target: "chunk:c1", relation: "generated" },
      ],
    };
    const { nodes } = coarsenGraph(withMixed);
    const chunkNode = nodes.find((n) => n.kind === "chunk");
    const itemStats = chunkNode?.itemStats;
    expect(itemStats?.["val_loss"]).toBeDefined();
    expect(itemStats?.["model_id"]).toBeUndefined();
  });

  it("leaves itemStats undefined for single-chunk nodes with no items", () => {
    const noItems: DataflowGraph = {
      level: "fine",
      truncated: false,
      nodes: [
        { id: "task:t1", kind: "task", label: "train", stats: { activity_id: "train" } },
        { id: "chunk:c1", kind: "chunk", label: "data", stats: {} },
      ],
      edges: [
        { source: "task:t1", target: "chunk:c1", relation: "generated" },
      ],
    };
    const { nodes } = coarsenGraph(noItems);
    const chunkNode = nodes.find((n) => n.kind === "chunk");
    expect(chunkNode?.itemStats).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// Tests: edge cases
// ---------------------------------------------------------------------------

describe("coarsenGraph — edge cases", () => {
  it("passes through an empty graph unchanged", () => {
    const empty: DataflowGraph = { level: "coarse", truncated: false, nodes: [], edges: [] };
    const result = coarsenGraph(empty);
    expect(result.nodes).toHaveLength(0);
    expect(result.edges).toHaveLength(0);
  });

  it("propagates truncated flag from the input graph", () => {
    const truncated: DataflowGraph = { level: "coarse", truncated: true, nodes: [], edges: [] };
    expect(coarsenGraph(truncated).truncated).toBe(true);
  });

  it("handles a chunk with no generator or consumer gracefully", () => {
    const orphan: DataflowGraph = {
      level: "coarse",
      truncated: false,
      nodes: [
        { id: "chunk:orphan", kind: "chunk", label: "mystery", stats: {} },
      ],
      edges: [],
    };
    const { nodes, edges } = coarsenGraph(orphan);
    expect(nodes).toHaveLength(1);
    expect(edges).toHaveLength(0);
  });
});
